spring.application.name=gdg
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
app.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:5173}
