package com.hackathon.gdg.global.error;

public enum ErrorCode {
	INVALID_REQUEST,
	ROOM_NOT_FOUND,
	ROOM_NOT_JOINABLE,
	DUPLICATE_NICKNAME,
	INVALID_TOKEN,
	ACCESS_DENIED,
	TOKEN_GENERATION_FAILED,
	ROOM_CODE_GENERATION_FAILED,
	INTERNAL_SERVER_ERROR
}
