package com.hackathon.gdg.global.error;

public enum ErrorCode {
	INVALID_REQUEST,
	ROOM_NOT_FOUND,
	ROOM_NOT_JOINABLE,
	DUPLICATE_NICKNAME,
	GAME_NOT_FOUND,
	GAME_INVALID_STATE,
	INSUFFICIENT_PARTICIPANTS,
	INVALID_SEEKER_COUNT,
	INVALID_GAME_ROLE,
	DESIGN_TIME_EXPIRED,
	CHARACTER_ALREADY_SUBMITTED,
	CHARACTER_NOT_FOUND,
	INVALID_IMAGE,
	STORAGE_ERROR,
	QR_GENERATION_FAILED,
	INVALID_TOKEN,
	ACCESS_DENIED,
	TOKEN_GENERATION_FAILED,
	ROOM_CODE_GENERATION_FAILED,
	INTERNAL_SERVER_ERROR
}
